### ISSUE TITLE
stock_indent module Installation Error

### ISSUE THREAD

**Issue by rjay1018** [Odoo-India/odoo-india#23]
Traceback (most recent call last):
  File "/opt/odoo/v8/server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v8/server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/v8/server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/v8/server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/v8/server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/v8/web/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/v8/web/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/v8/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/v8/server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/v8/server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/v8/server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/v8/server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/v8/server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/v8/server/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/v8/server/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/v8/server/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/v8/server/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/v8/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/v8/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/opt/odoo/v8/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/models.py", line 4074, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/v8/server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/models.py", line 4265, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/v8/server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/v8/server/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<field name="list_price">' cannot be located in parent view

Error context:
View `product.product.container.form`
[view_id: 308, xml_id: n/a, model: product.product, parent_id: 257]" while parsing /opt/odoo/v8/extra-addons/odoo-india-8.0/product_container/product_container_view.xml:6, near
<record id="view_product_container_form" model="ir.ui.view">
			<field name="name">product.product.container.form</field>
			<field name="model">product.product</field>
			<field name="inherit_id" ref="product.product_normal_form_view"/>
			<field name="arch" type="xml">
				<data><label for="sale_ok" position="after">
					<field name="container_ok" attrs="{'invisible':[('type','=','service')]}"/>
					<label for="container_ok" attrs="{'invisible':[('type','=','service')]}"/>
				</label>
				<field name="list_price" position="after">
					<field name="container_id" attrs="{'invisible':['|', ('container_ok','=',True), ('type','=','service')]}" context="{'default_container_ok': True}"/>
				</field>
			</data></field>
		</record>

**Comment by mga-odoo** [comment]
this is not supported with odoo version 8.0 and 9.0
